version: '3.8'


services:
#the backend
  api:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./final_weights:/app/final_weights
    networks:
      - X390-net



  #frontend
  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - X390-net

  #airflow container
  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    user: "1000:0"
    environment:
      - AIRFLOW_UID=1000

    ports:
      - "8080:8080"
    volumes:
      - ./:/opt/airflow
    #forcefully remove previous running PID and start ariflow
    command: bash -c "rm -f /opt/airflow/airflow-webserver.pid && airflow standalone"
    networks:
      - X390-net
 

networks:
  X390-net:
    driver: bridge
